### ISSUE TITLE
How to auto-hide navbar when we are on top like your official website

### ISSUE THREAD

**Issue by mohit01-beep** [praveenscience/Portfolio-LetsGrad#1]

**Comment by praveenscience** [comment]
@mohit01-beep Come tomorrow for that webinar! I'll show you the tips and tricks used in my next webinar: [Tips & Tricks used in my Portfolio](https://youtu.be/Kd2IAgT-orQ). Do check it out! And once you're convinced, close this issue! 😁

**Comment by praveenscience** [comment]
@mohit01-beep Are you in the Webinar? 😁 We're gonna answer your query! 🤘🏻
